### ISSUE TITLE
MacOS support: Unresolved dependencies

### ISSUE THREAD

**Issue by athei** [WowDevTools/Everlook#3]
I am trying to build Everlook on MacOS with newest Xamarin Studio (Monodevelop). I installed dependencies with nuget restore but still I have a lot of unresolved dependencies (see screenshot).

Am I doing something wrong or is MacOS just unsupported?
![screen shot 2017-03-07 at 11 36 04](https://cloud.githubusercontent.com/assets/2580396/23652737/50da9b6e-032a-11e7-8c7e-763f998d281e.png)

**Comment by Nihlus** [comment]
Hey there!

You're lacking the gtk-sharp-3 package on your system. You ought to be able to install it with Brew (as far as I've read, but I don't use MacOS myself). Please give that a go.

**Comment by athei** [comment]
There is no gtk-sharp or gtk-sharp-3 in brew. Isn't that a managed C# package? As this it should be installed with nuget and not with the native packet manager. I tried nuget install gtk-shark-3. I installed it. But it changed nothing.

**Comment by Nihlus** [comment]
You may need to compile from source. Everlook currently targets GTK# 2.99.3 on Windows and Mac, and uses the native Mono packages on Linux.

The source is available here (https://ftp.acc.umu.se/pub/gnome/sources/gtk-sharp/2.99/), and general information about how to get it, which version to choose, etc, is available here (http://www.mono-project.com/docs/gui/gtksharp/)

**Comment by Nihlus** [comment]
The NuGet packages are not officially supported, unfortunately, and as such I can't reliably use them.
